services:
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_models:/root/.ollama

  db-one: # NOTE: This MUST match this pattern: db-DB_SUFFIX, where DB_SUFFIX is defined in .env file
    image: pgvector/pgvector:pg17
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: d0kkm96s7stm/rag-backend:1.0
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db-${DB_SUFFIX}:5432/${DB_NAME}
      - OLLAMA_HOST=http://ollama:11434  # CHANGE THIS WHEN USING NATIVE HOST MAC-MINI GPUs
      - PYTHONUNBUFFERED=1
      - HF_TOKEN=${HF_TOKEN}
      - BACKEND_PORT=${BACKEND_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SUFFIX=${DB_SUFFIX}
    volumes:
      - ./docs:/app/docs
      - hf_cache:/root/.cache/huggingface
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - ollama # COMMENT THIS OUT WHEN USING NATIVE HOST MAC-MINI GPUs
      - db-${DB_SUFFIX}
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:${BACKEND_PORT}/health', timeout=2)"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 60s

  frontend:
    image: d0kkm96s7stm/rag-frontend:1.0
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - VITE_BACKEND_PORT=${BACKEND_PORT}
    stdin_open: true
    tty: true
    depends_on:
      backend:
        condition: service_healthy

volumes:
  hf_cache:
  ollama_models: # COMMENT THIS OUT WHEN USING NATIVE HOST MAC-MINI GPUs
  pgdata:

